INSERT INTO Symptoms (Name) VALUES
("Chest pain"),
("Neck pain"),
("Heartburn"),
("Nausea/Vomiting"),
("Dizziness"),
("Shortness of breath"),
("Fast or uneven heartbeat"),
("Discolored skin patches"),
("Dry sking"),
("Open sores"),
("Peeling skin")
("Acne"),
("Atopic Dermatitis"),
("Rashes"),
("Headaches"),
("Weakness or numbness in the limbs"),
("Altered sleep patterns"),
("Memory loss"),
("Paralysis"),
("Sensitivity to light"),
("Seizures"),
("Tremors"),
("Bleeding between periods"),
("Abnormal vaginal bleeding"),
("Pain in pelvis"),
("Urgent need to urinate"),
("Burning sensation during urination"),
("Blisters on genital area"),
("Pain during sex"),
("Sprain"),
("Swelling"),
("Bruise");
 